version: 2

updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      frontend-runtime:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "wagmi"
          - "viem"
          - "@rainbow-me/*"
      frontend-tooling:
        patterns:
          - "eslint*"
          - "typescript"
          - "tailwindcss"
          - "@types/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
