#!/usr/bin/env node
/**
 * Regenerates src/abis/*.ts from the compiled Foundry artifacts in ../contracts/out.
 *
 * Run `forge build` in ../contracts first, then:
 *   node scripts/generate-abis.mjs
 *
 * This keeps the frontend ABIs byte-for-byte derived from the real contracts instead of
 * hand-copied, so they can't silently drift. Each output file is plain generated TypeScript
 * (ABI array + `as const`) so wagmi/viem get full literal typing for reads and writes.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_OUT = join(__dirname, "..", "..", "contracts", "out");
const ABIS_DIR = join(__dirname, "..", "src", "abis");

// [artifact name in contracts/out, output basename, exported const name]
const TARGETS = [
  ["HalalToken", "HalalToken", "halalTokenAbi"],
  ["HalalVesting", "HalalVesting", "halalVestingAbi"],
  ["HalalPSM", "HalalPSM", "halalPsmAbi"],
  ["HalalDAO", "HalalDAO", "halalDaoAbi"],
  ["HalalTimelock", "HalalTimelock", "halalTimelockAbi"],
  ["CPIReportAdapter", "CPIReportAdapter", "cpiReportAdapterAbi"],
];

// Generic ERC20 ABI for the PSM's reserve token (e.g. DAI/USDC) - sourced from the compiled
// OpenZeppelin ERC20.sol artifact rather than hand-written, since it's a standard interface
// shared by any reserve token, not one of the five Halal contracts.
const ERC20_TARGET = ["ERC20", "ERC20", "erc20Abi"];

function generate([artifactName, outBasename, exportName]) {
  const artifactPath = join(CONTRACTS_OUT, `${artifactName}.sol`, `${artifactName}.json`);
  if (!existsSync(artifactPath)) {
    throw new Error(
      `Missing artifact: ${artifactPath}. Run "forge build" in the contracts/ directory first.`,
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const header =
    `// AUTO-GENERATED by app/scripts/generate-abis.mjs from\n` +
    `// contracts/out/${artifactName}.sol/${artifactName}.json — do not edit by hand.\n` +
    `// Regenerate with: cd contracts && forge build && cd ../app && node scripts/generate-abis.mjs\n\n`;
  const body = `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(ABIS_DIR, `${outBasename}.ts`), header + body);
  console.log(`wrote src/abis/${outBasename}.ts (${abi.length} ABI entries)`);
}

for (const target of TARGETS) generate(target);
generate(ERC20_TARGET);

console.log("Done.");
